<?php
use PHPUnit\Framework\TestCase;

class ConsoleWorkerTest extends TestCase
{
    public $console_worker;
    public function setUp(): void
    {
        $this->console_worker = new ConsoleWorker();
    }

    public function testConstruct()
    {
        global $argv;
        $GLOBALS['argv']=array(
            'argv_test.php',
            'show_today',
        );
        $GLOBALS['argc']=count($argv);
        $expected_command = 'show_today';
        $testClass = new ConsoleWorker();
        $this->assertEquals($expected_command, $testClass->command);
    }

    public function testTodayBudget()
    {
        $return_string = $this->console_worker->showTodayBudget();
        $date = date("d m Y");
        $expected_string = "Hello! Your budget for $date is";
        $this->assertSame($expected_string, $return_string);
    }

    public function testCheckAndRunCommand()
    {
        global $argv;
        $GLOBALS['argv']=array(
            'argv_test.php',
            'show_today',
        );
        $GLOBALS['argc']=count($argv);
        $testClass = new ConsoleWorker();
        $date = date("d m Y");
        $expected_string = "Hello! Your budget for $date is";
        $this->expectOutputString($expected_string);
        $testClass->checkAndRunCommand();
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
