<?php
use PHPUnit\Framework\TestCase;

class ConsoleWorkerTest extends TestCase
{
    public $console_worker;
    public function setUp(): void
    {
        $this->console_worker = new ConsoleWorker();
    }

    public function testConstruct()
    {
        //ToDo dont know how to test cli\line also
        $expected_string = "Hello!\n";
        $this->expectOutputString($expected_string);
    }

    public function testTodayBudget()
    {
        $return_string = $this->console_worker->showTodayBudget();
        $date = date("d m Y");
        $expected_string = "Your budget for $date is";
        $this->assertSame($expected_string, $return_string);
    }

    public function getStartQuestion()
    {
        //ToDO really dont know how to test input for this library
    }

    public function testChechAndRunCommand()
    {
        $this->console_worker->command = 'show_today';
        $date = date("d m Y");
        $expected_string = "Your budget for $date is";
        $this->assertEquals($expected_string, $this->console_worker->checkAndRunCommand());

        $this->console_worker->command = '';
        $expected_string = "Please, enter correct command";
        $this->assertEquals($expected_string, $this->console_worker->checkAndRunCommand());
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
